package com.everis.compute.model;
// Generated 8/10/2019 11:26:50 AM by Hibernate Tools 5.2.12.Final



/**
 * Cliente generated by hbm2java
 */

public class Cliente implements java.io.Serializable {

	
	private int idcliente;
	private String nombre;
	private Integer tipocliente;

	public Cliente() {
	}

	public Cliente(int idcliente) {
		this.idcliente = idcliente;
	}

	public Cliente(int idcliente, String nombre, Integer tipocliente) {
		this.idcliente = idcliente;
		this.nombre = nombre;
		this.tipocliente = tipocliente;
	}

	
	public int getIdcliente() {
		return this.idcliente;
	}

	public void setIdcliente(int idcliente) {
		this.idcliente = idcliente;
	}


	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}


	public Integer getTipocliente() {
		return this.tipocliente;
	}

	public void setTipocliente(Integer tipocliente) {
		this.tipocliente = tipocliente;
	}

}
