package com.everis.quotation.model;
// Generated 8/10/2019 11:26:50 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "cliente", catalog = "examenequipodos")
public class Cliente implements java.io.Serializable {

	
	private int idcliente;
	private String nombre;
	private Integer tipocliente;

	public Cliente() {
	}

	public Cliente(int idcliente) {
		this.idcliente = idcliente;
	}

	public Cliente(int idcliente, String nombre, Integer tipocliente) {
		this.idcliente = idcliente;
		this.nombre = nombre;
		this.tipocliente = tipocliente;
	}

	@Id
	//@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idcliente", unique = true, nullable = false)
	public int getIdcliente() {
		return this.idcliente;
	}

	public void setIdcliente(int idcliente) {
		this.idcliente = idcliente;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "tipocliente")
	public Integer getTipocliente() {
		return this.tipocliente;
	}

	public void setTipocliente(Integer tipocliente) {
		this.tipocliente = tipocliente;
	}

}
