package com.everis.quotation.model;
// Generated 8/10/2019 11:26:50 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Servicio generated by hbm2java
 */
@Entity
@Table(name = "servicio", catalog = "examenequipodos")
public class Servicio implements java.io.Serializable {

	private int idservicio;
	private String nombre;
	private Double precio;

	public Servicio() {
	}

	public Servicio(int idservicio) {
		this.idservicio = idservicio;
	}

	public Servicio(int idservicio, String nombre, Double precio) {
		this.idservicio = idservicio;
		this.nombre = nombre;
		this.precio = precio;
	}

	@Id

	@Column(name = "idservicio", unique = true, nullable = false)
	public int getIdservicio() {
		return this.idservicio;
	}

	public void setIdservicio(int idservicio) {
		this.idservicio = idservicio;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "precio", precision = 22, scale = 0)
	public Double getPrecio() {
		return this.precio;
	}

	public void setPrecio(Double precio) {
		this.precio = precio;
	}

}
